services:

  db:
    image: postgres:13.4-alpine
    container_name: db
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    # build: .
    image: asp781/ekranstroy:latest
    ports:
      - "8000:8000"
    container_name: web
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

  redis:
    container_name: redis
    image: redis:alpine
    restart: always


volumes:
  static_value:
  media_value:
