version: '3.8'

services:

  db:

    image: postgres:13.4-alpine
    container_name: db
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    # build: .
    image: asp781/ekranstroy:latest
    ports:
      - "8000:8000"
    container_name: web
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - html:/app/
      - ./xlsx/Сметы.xlsx:/app/secret2/management/commands/Сметы.xlsx
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /html:/var/www/certbot
      - ./nginx/dhparam/dhparam.pem:/etc/nginx/dhparam/dhparam.pem
      - etc-letsencrypt:/etc/letsencrypt
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - html:/var/html/
    depends_on:
      - web

  redis:
    container_name: redis
    image: redis:alpine
    restart: always

volumes:
  static_value:
  media_value:
  etc-letsencrypt:
  html:
