# Generated by Django 4.2.9 on 2025-02-09 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('total_price', models.CharField(max_length=10)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret2.estimate')),
            ],
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('total_price', models.CharField(max_length=10)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret2.estimate')),
            ],
        ),
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('total_price', models.CharField(max_length=10)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret2.estimate')),
            ],
        ),
    ]
