# Generated by Django 4.2.9 on 2025-02-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='date',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
