# Generated by Django 4.2.9 on 2025-02-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret2', '0002_alter_paid_date_alter_purchased_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed',
            name='amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='completed',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='completed',
            name='total_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='completed',
            name='unit',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paid',
            name='amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paid',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paid',
            name='total_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paid',
            name='unit',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='unit',
            field=models.CharField(max_length=255),
        ),
    ]
